apiVersion: v1
kind: Pod
metadata:
  name: redis-pod
  labels: 
    name: redis-pod
    app: demo-voting-app
spec:
  containers: 
    - name: redis
      image: redis
      port:  #port to be exposed
        - containerPort: 6379    

# port is 6379 because that's the defualt port that redis exposes