apiVersion: v1
kind: Pod
metadata:
  name: result-app-pod
  labels: 
    name: result-app-pod
    app: demo-voting-app
spec:
  containers: 
    - name: result-app
      image: dockersamples/examplevotingapp_result
      port:  #port to be exposed
        - containerPort: 80    

# result app exposes port 80 because it's a web application